<a href="https://colab.research.google.com/github/Aseel-Mira/project1/blob/main/Python3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

Is an open-source Python library that provides high-performance, easy-to-use data structure, and data analysis tools for the Python programming language.

In [ ]:
import pandas as pd
d = {'Name': ['Mohammed', 'Fatima', 'Ali', 'Ibrahim'],
     'Age': [30, 32, 36, 40], 
     'Education_level': ['Phd', 'Master', 'Bachelor', 'Phd']}

d


{'Name': ['Mohammed', 'Fatima', 'Ali', 'Ibrahim'],
 'Age': [30, 32, 36, 40],
 'Education_level': ['Phd', 'Master', 'Bachelor', 'Phd']}

In [ ]:
df = pd.DataFrame(d)

df

Name  Age Education_level
0  Mohammed   30             Phd
1    Fatima   32          Master
2       Ali   36        Bachelor
3   Ibrahim   40             Phd

# Numpy

It's a Python library used for working with arrays.

In [ ]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_list)
print(my_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.zeros((3, 2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.full((3, 5), 6, dtype=int)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [ ]:
np.arange(2, 8)

array([2, 3, 4, 5, 6, 7])

In [ ]:
np.random.normal( 1,3, (3,3) )

array([[-1.37256238,  0.37840096,  2.0889742 ],
       [-6.85237516, -0.84622702, -1.47368334],
       [-4.03413124,  4.64557911,  2.18047544]])

In [ ]:
np.random.randint( 20,60, (5,5) )

array([[39, 20, 57, 45, 54],
       [58, 46, 36, 20, 35],
       [24, 36, 40, 55, 31],
       [56, 42, 20, 25, 50],
       [39, 37, 35, 21, 57]])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.empty((3,3))

array([[1.37256238, 0.37840096, 2.0889742 ],
       [6.85237516, 0.84622702, 1.47368334],
       [4.03413124, 4.64557911, 2.18047544]])

# API

Application Programming Interface:

An intermediary between the server and the client.





1- RESTful API:

It is a type of API, but a RESTful API uses a set of protocols or a set of guidelines, so that the client must follow those protocols when communicating with the RESTful API.

(GET, POST, PUT, DELETE)

In [ ]:
import requests

requests.get('http://randumuser.me/api/')

<Response [200]>

2- JSON:

It is just a way to write or to form data.